### ISSUE TITLE
Node Version Not in Log when it is Downloaded

### ISSUE THREAD

**Issue by dizmond** [comp426-2022-fall/a00#10]
#### What is happening?
When I type node -v in the console, my **node version is v16.17.0** and when I type **nvm -v it is version 1.1.9**.
However, it **doesn't display in the final Log file** or the command prompt when I run the install_check.sh script.

I was having a lot of issues earlier with installing nvm the way described in the ReadMe because I already had nvm installed somewhere. I followed directions to uninstall it. Then, the curl command worked after that. But the nvm commands weren't recognized in the command prompt. So I installed it manually following these directions:

https://github.com/coreybutler/nvm-windows
https://github.com/coreybutler/nvm-windows/releases

After that, I used some nvm command to install the specific version 16.17.0 (nvm install 16.17.0) because --lts was an unrecognized command for my command prompt. Then (nvm use 16.17.0). 

**My main question is:** It looks to be downloaded on my end. Do I have to worry about the Log not having the Node version listed? If so, how can I fix this?

#### Screenshots
![image](https://user-images.githubusercontent.com/74222950/185985280-0b7e7d0d-2c50-4d8a-beaf-654768044204.png)
![image](https://user-images.githubusercontent.com/74222950/185985301-0d00e670-0ee7-42b1-9bf6-06001c0014b3.png)

**Comment by jdmar3** [comment]
The links that you have above are to nvm-windows, which is not a package that you should be installing. The NVM that we're looking to install will only install inside WSL, because it is for UNIX/Posix systems (MacOS, Linux). NVM-windows will only install on Windows, and it an entirely different package.

This is the NVM you should be installing: https://github.com/nvm-sh/nvm

**Comment by jdmar3** [comment]
It also looks like you are running in PowerShell directly on Windows and not using WSL, which is not going to work.

**Comment by dizmond** [comment]
Using WSL solved all of my issues. I didn't realize that that is what we were using. Everything is installed correctly now and it shows in my Log.

**Comment by jdmar3** [comment]
Great!
