### ISSUE TITLE
Log file added to the master branch, not the main one and therefore not passing autograder

### ISSUE THREAD

**Issue by rcpang2024** [comp426-2022-fall/a00#11]
I'm able to successfully create a log file for a00, however everytime I commit and push, it seems to be going to the master branch instead of the main branch. I'm still not passing the autograder and I'm not sure why I'm pushing in master but not to main because I followed all of the steps on the README. 

Here's what I have for master:
![image](https://user-images.githubusercontent.com/69740294/186007060-200c4adf-f151-4bf0-97f6-b40ed0e04723.png)

Here's what I have under main:
![image](https://user-images.githubusercontent.com/69740294/186007207-907f2831-d488-491a-b16d-56f0678a121f.png)

**Comment by jdmar3** [comment]
There should not be a "master" branch at all. The default in the GitHub org should be "main," so when you cloned it initially, only the main branch should be there. But, however it happened, you can click that big green "Compare & pull request" button and merge into main and see what happens.

**Comment by rcpang2024** [comment]
I tried merging it using the method you described but no option to merge came up. I googled around online and tried a variety of things. However, now I have this problem:
![image](https://user-images.githubusercontent.com/69740294/186045710-c469db38-f14c-4a1c-8eb9-d1106de71158.png)
I don't understand why it's giving me this error message.

**Comment by jdmar3** [comment]
That repository doesn't exist. That is why. Where is your repository on GitHub? Please post a link.
