### ISSUE TITLE
Clarification needed: ./install_check.sh outputting Permission Denied

### ISSUE THREAD

**Issue by areebakhokhar** [comp426-2022-fall/a00#12]
<img width="569" alt="Screen Shot 2022-08-22 at 4 28 44 PM" src="https://user-images.githubusercontent.com/69765710/186013000-c1f600da-2aec-49f6-99aa-5c4b62aef76e.png">

When I try to run the script: ./install_check.sh I keep getting permission denied. I'm not sure why.

Thanks!

**Comment by jdmar3** [comment]
This is a runtime error

Run `ls -lah` in that directory and post the output. 

The most likely problem is that that the mode needs to be set to execute this script. 

If the output from `ls -lah` doesn't have any x's in the leftmost column, then you can run: `chmod +x` and then after that you'll be able to run `./install_check.sh` and it will run.

**Comment by areebakhokhar** [comment]
<img width="572" alt="Screen Shot 2022-08-22 at 5 15 10 PM" src="https://user-images.githubusercontent.com/69765710/186020425-510b83fa-5fc5-4df6-91d5-ce78ccde6cf9.png">

I don't see any x's, but when I run chmod +x it still says permission denied. also when i run ls -lah the output doesn't change from what it was originally.

**Comment by jdmar3** [comment]
`chmod +x ./install_check.sh`

I should have specified that you have to run it _on_ the file you are trying to give execute mode to. It should have output an error if you ran it without a target, something like this: 
```
chmod: missing operand after ‘+x’
Try 'chmod --help' for more information.
```

**Comment by areebakhokhar** [comment]
this worked, thank you!
