### ISSUE TITLE
RUNTIME ERROR: can't change SHELL to bin/bash (Mac)

### ISSUE THREAD

**Issue by XimenaColopy** [comp426-2022-fall/a00#13]
I am trying to change my shell from bin/zsh to bin/bash. "chsh -s /bin/bash" doesn't seem to be working. 

<img width="560" alt="Screen Shot 2022-08-22 at 4 35 42 PM" src="https://user-images.githubusercontent.com/43392764/186013956-810feda4-5593-4df6-9c4b-de169622e75b.png">

any ideas?

**Comment by jdmar3** [comment]
What does ` which bash` say?

**Comment by luisdrg** [comment]
Go to System Preferences > Users and Groups

On the bottom left you will see a lock icon that says "Click the lock to make changes" (You will need to input your password).

Now, press and hold the "control" key and click on your user. This will prompt "Advanced Options..." Click on that.

Find where it says "Login shell" and select "/bin/bash"

Finally, click "OK"

That should do the trick!!


EDIT: Found another method
https://support.apple.com/en-hk/guide/terminal/trml113/mac
