### ISSUE TITLE
Clarification needed: [SHORT DESCRIPTION OF CONFUSING THING]

### ISSUE THREAD

**Issue by mayather** [comp426-2022-fall/a00#14]
When going through the Finish the Assignment section, I accidentally skipped step two and created the directory before I cloned. I attached what I entered. How do I fix this?
<img width="644" alt="Capture" src="https://user-images.githubusercontent.com/69762402/186024682-3437c24d-d6ca-4589-ab33-f5f313f1c681.PNG">

**Comment by jdmar3** [comment]
Do `ls` to see what subdirectories are there. You're just using the wrong directory name.
