### ISSUE TITLE
Clarification needed: does this seem correct?

### ISSUE THREAD

**Issue by yantangyantang** [comp426-2022-fall/a00#15]
Hi, just hoping to check if this seem correct and complete for 1st assignment? Also how do I know if its passed the autogravder? Thanks!
![image](https://user-images.githubusercontent.com/89480267/186041157-6d08278f-aab9-4eae-a88f-bfeaeb68bd9f.png)

**Comment by jdmar3** [comment]
I'm not sure what you're asking here. I'm closing this issue until you provide more information.
