### ISSUE TITLE
ERROR: Permission to comp426-2022-fall/a00.git denied

### ISSUE THREAD

**Issue by mayather** [comp426-2022-fall/a00#16]
I'm getting an error which says "Warning: Permanently added the ECDSA host key for IP address '140.82.112.4' to the list of known hosts.
ERROR: Permission to comp426-2022-fall/a00.git denied to mayather.
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists"
when I try to push to github. I've looked online and it says it may be an issue with the key, but I've confirmed the key is correct to the best of my knowledge. 

Also, I mistakenly tried downloading some of the software using the command prompt, and I had created a key there and added it to my github account. After realizing I was supposed to use Ubuntu, I deleted the old key and added the new one. Could this be causing the error?
<img width="959" alt="Capture 2" src="https://user-images.githubusercontent.com/69762402/186042430-4cb12430-b7d3-472c-9dc9-2a2610b83d00.PNG">
<img width="665" alt="Capture 3" src="https://user-images.githubusercontent.com/69762402/186042443-99d46a72-ad6c-4029-ba46-c5781a60b5a4.PNG">

**Comment by luisdrg** [comment]
It was stated that: "If you clone this repo directly, it will not be added to the organization as an individual repo associated with your account and you will not be able to push to it."

Perhaps you cloned the repository directly?

Make sure to use the GitHub classroom link instead: https://classroom.github.com/a/TLIqqWVj

**Comment by jdmar3** [comment]
It would appear that you have not set up an ssh key in GitHub settings. It also absolutely looks like you have cloned the repo from the template, which it explicitly states not to do. Please follow the instructions and use the invite link and you should be able to get through the assignment.
