### ISSUE TITLE
Autograder: log file

### ISSUE THREAD

**Issue by yantangyantang** [comp426-2022-fall/a00#18]
autograder failed at checking log file however it seems I had that log file already. Please help advise.  Thanks!
![image](https://user-images.githubusercontent.com/89480267/186047719-98230a70-9243-49cb-af7b-5c99ff5ce38a.png)

![image](https://user-images.githubusercontent.com/89480267/186047945-e0b19879-e675-4205-a968-3bdd91caffc1.png)

**Comment by jdmar3** [comment]
I need you to post a link to your assignment repository actions page so I can see what is going on.

**Comment by yantangyantang** [comment]
> 

https://github.com/comp426-2022-fall/a00-onboarding-yantangyantang/actions
Thank you!

**Comment by jdmar3** [comment]
The run passed, so there is no problem. Right? https://github.com/comp426-2022-fall/a00-onboarding-yantangyantang/runs/7963433201?check_suite_focus=true
