### ISSUE TITLE
Clarification needed: Log file has different System owner name 

### ISSUE THREAD

**Issue by velichet** [comp426-2022-fall/a00#19]
I am pushing my log file to complete my assignment. However , the Macbook I am currently belongs to my brother until I buy a new one. I have created a new admin login however the system ownership remains with him. Is it okay if I push these changes with his name in System owner section of the log files ?

**Comment by jdmar3** [comment]
This is not a thing that you have to worry about. GitHub only cares about the GitHub user (or really the name and email address that is associated with a given commit.
