### ISSUE TITLE
Error when attempting to access Public ssh key

### ISSUE THREAD

**Issue by calebbg** [comp426-2022-fall/a00#20]
I'm attempting to do step 2 under "Set up SSH keys", but when I paste the commands provided I get an error saying "ssh-rsa: command not found".
![public key error](https://user-images.githubusercontent.com/69723467/186165173-3136fd81-fa84-471f-8f7e-7daffc26d5e5.JPG)

Any ideas what might cause this issue?

**Comment by jdmar3** [comment]
The public key is right there as the output of your first command. What are you trying to do with the second command? It looks like you have just pasted the key back into the command prompt and then added a nonexistent user@host identifier and then also another `cat` but none of that makes any sense.

The `cat ~/.ssh/id_rsa.pub` gives you your public key on STDOUT. That is what you then place in the key settings in your GitHub account. 

If you are logged in, you can access that directly by going here: https://github.com/settings/keys

**Comment by calebbg** [comment]
Okay I see what my point of confusion was. In the instructions it has this:
![image](https://user-images.githubusercontent.com/69723467/186250960-1957ec63-9a8e-4e8d-b04f-32f2a01ad459.png)

I interpreted this as meaning we were supposed to copy everything in the box, which command line takes as two separate commands since there are two lines. If I now understand correctly, we are simply supposed to use the cat command and the line after that in the image is just an example output. Is this correct?
