### ISSUE TITLE
Clarification needed: How do we know when we've passed the autograder?

### ISSUE THREAD

**Issue by rileysho01** [comp426-2022-fall/a00#21]
I think I finished my assignment yesterday, but I can't seem to figure out how to access the results of the autograder. I was hoping I could just have a refresh of the instructions for checking the autograder? Thank you!

**Comment by jdmar3** [comment]
Look at the Actions tab on your GitHub assignment repository. The log of all the action runs is there. If there is a green check next to the last one (at the top), then it passed. If it is a red X, then it has not passed. If you click on the individual runs they will show you more information, like a complete log of the run. 

See #29
