### ISSUE TITLE
Autograder: Check for log file 

### ISSUE THREAD

**Issue by sarahalhajli** [comp426-2022-fall/a00#22]
I added the log file to the main branch, but the autograder is failing to check for log file: https://github.com/comp426-2022-fall/a00-onboarding-sarahalhajli/actions
I'm not sure why this is happening, and checked previous similar issues but haven't been able to resolve this:

<img width="1394" alt="autograder action" src="https://user-images.githubusercontent.com/77937736/186460517-950a0533-b38f-4755-bf79-326b833d7740.png">
<img width="1661" alt="autgrading workflow" src="https://user-images.githubusercontent.com/77937736/186460538-2b7da9d6-cff7-4310-8305-a573b0910448.png">

**Comment by jdmar3** [comment]
There is no problem here. Your last push passed the autograder checks.

**Comment by bdhack23** [comment]
I am having a similar issue, so as long as we pass that one autograder test called "Added log file," we are good? That is what it is looking like based on this issue posting, but I wanted to make sure.
