### ISSUE TITLE
Unable to find install_check.sh file even though I added it to the repo

### ISSUE THREAD

**Issue by namitak8** [comp426-2022-fall/a00#23]
I added the install_check.sh file to my local repo, but I'm still getting an error saying that there is no such file or directory. 

![Install_check](https://user-images.githubusercontent.com/69767905/186539986-32fd52ac-31fc-4525-b8d6-4eeb5953fee8.png)

![Bash  install_check sh](https://user-images.githubusercontent.com/69767905/186539991-224845d5-46a9-45f6-b381-ba9abf591bfa.png)

**Comment by Evehe719** [comment]
Yea I have the same question.

It said "bash: ./install_check.sh: No such file or directory"

**Comment by micahlittle** [comment]
im also having this problem

**Comment by SpencerTwiddy** [comment]
Where did you get the install_check.sh file? I don't even have that, adding it is not mentioned in the assignment

**Comment by jdmar3** [comment]
If you put it in your repository on GitHub, you then must do `git pull` to get it to your local repo.

The issue about this is here: #2
