### ISSUE TITLE
Clarification needed: Cannot access bash terminal is wsl 

### ISSUE THREAD

**Issue by andrewyang24** [comp426-2022-fall/a00#24]
If there is something that seems off in the instructions , go through this checklist:

1. [ ] Is there an error in the text?
    - If yes, go to #2. 
    - If no, go to #3.
2. [ ] Did you create a pull request with a correction for the error?
    - If yes, then don't create an issue.
    - If no, then create a pull request with a suggested correction.
3. [ ] Did you read any documentation related to the thing that needs clarifying?
4. [ ] Did you Google the thing that needs clarifying?
5. [ ] Did you search or read through the other issues on this repo to make sure there isn't already a related issue?

None of the above, create an issue
------------------------------------------------------------------

Make sure to add **all the information needed to understand the error** so that someone can help. If the info is missing we'll add the 'Needs more information' label and close the issue until there is enough information.

- [ ] Provide URL of the file with the confusing thing.
- [ ] Identify the line number(s) in the file where the cunfusing thing is. 
- [ ] Describe what you find confusing?
- [ ] Take a guess and describe what you think the confusing thing might mean?

Delete text above this line before you submit your issue. Place your issue information in the appropriate sections below. 

#### URL of file with confusing thing
https://github.com/comp426-2022-fall/a00-onboarding-andrewyang24

#### Line number of confusing thing
1. You can install most everything you need all at once:
$ sudo apt install vim git curl

#### What is confusing?
After installing wsl and entering the wsl environment, I unable to proceed with the rest of the onboarding steps. I checked that I installed it with administrative privileges, and I went through the ubuntu login process. The error shows:
bash: sudo: command not found
<img width="680" alt="basherror" src="https://user-images.githubusercontent.com/69828496/186547854-705700ea-a754-4688-9f64-cb2862cc6cdd.png">

#### What do you think the confusing thing means?
I believe I am logged in as the root user, but I'm trying to get to bash ($). I'm unsure how to do so and I couldn't find any solutions online that have worked.

**Comment by jdmar3** [comment]
If you run `wsl` in your windows shell/powershell, then you are automatically using Bash because that is the shell for your Linux environment. If you want to see what shell the current user is assigned run `echo $SHELL`. It looks like you may not have created a non-root user. In the WSL install tutorials that are linked from the assignment it walks you through creating a regular user.
