### ISSUE TITLE
Can not run the script and then push the output back to GitHub

### ISSUE THREAD

**Issue by Evehe719** [comp426-2022-fall/a00#26]
I did all the listed according to the explanation but met a problem in the last run. 
And used the "ls" double check, but it still failed and say "No such file or director"

![2811661390331_ pic](https://user-images.githubusercontent.com/104244806/186552840-16bf6e88-faef-40aa-8788-d8d2a9a4b806.jpg)

**Comment by jdmar3** [comment]
See #2
