### ISSUE TITLE
Clarification needed: [How to know if you passed the autograder]

### ISSUE THREAD

**Issue by mayather** [comp426-2022-fall/a00#29]
To clarify, as long as we have a green check for the most recent autograder commit, we have passed with 100 on the autograder?
<img width="715" alt="Capture 4" src="https://user-images.githubusercontent.com/69762402/186739700-2848ea4b-07de-4a89-90ff-2080d14af4b0.PNG">

**Comment by jdmar3** [comment]
That is correct. It is a persistent log. The last one is the one that gets recorded.
