### ISSUE TITLE
Issues installing nvm

### ISSUE THREAD

**Issue by jdmar3** [comp426-2022-fall/a00#7]
### Discussed in https://github.com/orgs/comp426-2022-fall/discussions/8

<div type='discussions-op-text'>

<sup>Originally posted by **irachandra** August 18, 2022</sup>
So nvm installs correctly but after that it isn't able to locate it, I already tried restarting my terminal.
here's a screenshot of my terminal... any suggestions as to where I am going wrong?

<img width="672" alt="Screen Shot 2022-08-18 at 4 44 07 PM" src="https://user-images.githubusercontent.com/77810702/185491217-5ec90aab-7a29-4ecb-91e0-5c2e8e5bf3ea.png">

</div>

**Comment by jdmar3** [comment]
@irachandra, What happens when you look into the ~/.nvm directory? 

Can you do `ls -lah ~/.nvm` and post the output?

**Comment by raghuvarapadma** [comment]
I am having the same issue and I ran that command, here is my output: 

![image](https://user-images.githubusercontent.com/59041434/185820126-8b9a24b0-de67-4972-aabb-41b64a9d1489.png)

**Comment by raghuvarapadma** [comment]
Nevermind, turns out if you run `. ~/.nvm/nvm.sh` and then run `nvm install --lts`, you should be good! If that does not work, check out this section and try running through these tips: https://github.com/nvm-sh/nvm#troubleshooting-on-linux.

**Comment by irachandra** [comment]
Yea mine ended up working thanks!
