### ISSUE TITLE
Error: [Failed to git push at the last step]

### ISSUE THREAD

**Issue by xzkxu** [comp426-2022-fall/a00#9]
I was down to the last step and I am not able to push the changes I made to my repository to the github
<img width="1126" alt="WeChat235a601b7661e7104a78656e03497c0a" src="https://user-images.githubusercontent.com/98487016/185944111-26e29477-fd07-4255-b5bf-483126f0141b.png">
.

**Comment by jdmar3** [comment]
Try this: https://letmegooglethat.com/?q=git+error+you+have+not+concluded+your+merge+(merge_head+exists)

I'm posting this link because the error is right there in the message. What was one of the things in the checklist I gave you to create an issue? _Google the error message._

**Comment by jdmar3** [comment]
Post the output from the following: 

```
git status
git log
```

**Comment by xzkxu** [comment]
I tried to Google some ways, but the errors I don't recognize just getting more and more. So I solve the problem by recloning the repository with the "install_check.sh" file to my computer, and it can push onto GitHub this time. So I guess it is probably because my GitHub didn't have the "install_check.sh" file before but I have it on my computer workspace so it won't let me do git push.
